@echo off
cd /d "%~dp0"
title BillTea Android App Launcher
cls

echo ======================================================================
echo            Welcome to the BillTea Android App Launcher
echo ======================================================================
echo.

:: 1. Check for backend environment file
if not exist "server\.env" (
    echo [!] Server environment file .env not found.
    echo [*] Creating 'server\.env' from 'server\.env.example'...
    copy "server\.env.example" "server\.env" >nul
    echo.
    echo ----------------------------------------------------------------------
    echo [WARNING] IMPORTANT CONFIGURATION REQUIRED [WARNING]
    echo ----------------------------------------------------------------------
    echo A new '.env' file has been created in the 'server' folder.
    echo Please update the DATABASE_URL with your PostgreSQL database password.
    echo.
    echo Opening 'server\.env' in Notepad for you now...
    start notepad "server\.env"
    echo.
    echo Press any key AFTER you have saved and closed the '.env' file.
    pause >nul
    echo.
)

:: 2. Detect Local IP Address and Configure Mobile Env
echo [*] Detecting your local IPv4 address...
set LOCAL_IP=127.0.0.1
for /f "usebackq tokens=*" %%i in (`powershell -NoProfile -Command "(Get-NetIPAddress -AddressFamily IPv4 | Where IPAddress -NotLike '127.*' | Where IPAddress -NotLike '169.254.*' | Select-Object -First 1).IPAddress"`) do set LOCAL_IP=%%i

echo [SUCCESS] Detected local network IP address: %LOCAL_IP%
echo [*] Creating/updating 'mobile\.env' with API endpoint pointing to: http://%LOCAL_IP%:5000/api/v1
(
    echo # Auto-generated by run_android.bat
    echo EXPO_PUBLIC_API_URL=http://%LOCAL_IP%:5000/api/v1
) > "mobile\.env"
echo [SUCCESS] 'mobile\.env' configured successfully.
echo.

:: 3. Check and install Server dependencies
if not exist "server\node_modules" (
    echo [*] Backend dependencies node_modules not found. Installing...
    cd server
    call npm install
    cd ..
    echo [SUCCESS] Backend packages installed successfully.
    echo.
) else (
    echo [*] Backend dependencies already installed. Skipping...
)

:: 4. Check and install Mobile dependencies
if not exist "mobile\node_modules" (
    echo [*] Mobile dependencies node_modules not found. Installing...
    cd mobile
    call npm install
    cd ..
    echo [SUCCESS] Mobile packages installed successfully.
    echo.
) else (
    echo [*] Mobile dependencies already installed. Skipping...
)

:: 5. Generate Prisma Client
echo [*] Generating Prisma Client...
cd server
call npm run prisma:generate
cd ..
echo [SUCCESS] Prisma Client generated.
echo.

:: 6. Auto Run Database Migrations if password is set
findstr /C:"DATABASE_URL" "server\.env" | findstr "YOUR_PASSWORD_HERE" >nul
if %errorlevel% equ 0 (
    echo ----------------------------------------------------------------------
    echo [WARNING] DATABASE NOT MIGRATED [WARNING]
    echo ----------------------------------------------------------------------
    echo You have not updated your database password in 'server\.env'.
    echo Please edit 'server\.env' and enter your PostgreSQL password,
    echo then restart this script.
    echo.
    pause
    exit /b
)

echo [*] Checking database migrations...
cd server
call npx prisma migrate deploy
if %errorlevel% neq 0 (
    echo.
    echo [ERROR] Database migration failed with code %errorlevel%.
    echo Please resolve the migration issues and restart this script.
    cd ..
    pause
    exit /b %errorlevel%
)
echo [*] Ensuring default database records exist ^(seeding^)...
call npm run prisma:seed
if %errorlevel% neq 0 (
    echo.
    echo [ERROR] Database seeding failed with code %errorlevel%.
    cd ..
    pause
    exit /b %errorlevel%
)
cd ..
echo [SUCCESS] Database migrations and seeding applied.
echo.

:: 7. Check for running Android Emulator / Start one automatically
echo [*] Checking for active Android Emulators...

if "%ANDROID_HOME%"=="" (
    if exist "%LOCALAPPDATA%\Android\Sdk" (
        set "ANDROID_HOME=%LOCALAPPDATA%\Android\Sdk"
        echo [*] Auto-detected ANDROID_HOME at %LOCALAPPDATA%\Android\Sdk
    )
)

if not "%ANDROID_HOME%"=="" (
    "%ANDROID_HOME%\platform-tools\adb.exe" devices | findstr "emulator" >nul
    if %errorlevel% neq 0 (
        echo [*] No running emulator detected. Finding available virtual devices...
        set FIRST_AVD=
        for /f "usebackq tokens=*" %%a in (`"%ANDROID_HOME%\emulator\emulator.exe" -list-avds`) do set FIRST_AVD=%%a
        
        if not "%FIRST_AVD%"=="" (
            echo [*] Launching Android Emulator: %FIRST_AVD%...
            start "" "%ANDROID_HOME%\emulator\emulator.exe" -avd %FIRST_AVD%
            echo [*] Waiting 5 seconds for emulator to start...
            timeout /t 5 >nul
        ) else (
            echo [WARNING] No Android Virtual Devices AVD found.
            echo           Please create an emulator in Android Studio Device Manager.
        )
    ) else (
        echo [SUCCESS] Running emulator detected.
    )
) else (
    echo [WARNING] ANDROID_HOME environment variable is not defined.
    echo           Cannot automatically start the Android Emulator.
)
echo.

echo ======================================================================
echo Starting Backend Server and Expo Android App...
echo ======================================================================
echo.

:: Start NestJS Backend Server in a new window
start "BillTea Backend Server" cmd /k "title BillTea Backend Server && cd server && echo Starting NestJS backend... && npm run start:dev"

:: Start Expo Mobile App in a new window
start "BillTea Mobile App" cmd /k "title BillTea Mobile App && cd mobile && echo Starting Expo Metro Bundler for Android... && npm run android"

echo.
echo ======================================================================
echo Startup complete! Both servers are running in separate windows.
echo    - Backend API: http://%LOCAL_IP%:5000/api/v1
echo    - Swagger Docs: http://%LOCAL_IP%:5000/api/docs
echo.
echo    For physical testing (Expo Go):
echo    1. Connect your phone to the same Wi-Fi network: (IP: %LOCAL_IP%)
echo    2. Scan the QR code appearing in the "BillTea Mobile App" terminal window.
echo ======================================================================
pause